create table if not exists tracking (
    req_id integer primary key autoincrement not null,
    Accept text,
    Accept_Charset text,
    Accept_Encoding text,
    Accept_Language text,
    Accept_Datetime text,
    Authorization text,
    Cache_Control text,
    Connection text,
    Cookie text,
    Content_Length text,
    Content_MD5 text,
    Content_Type text,
    Req_Date text,
    Expect text,
    Forwarded text,
    Req_From text,
    Host text,
    Req_If_Match text,
    Req_If_Modified_Since text,
    Req_If_None_Match text,
    Req_If_Range text,
    Req_If_Unmodified_Since text,
    Max_Forwards integer,
    Origin text,
    Pragma text,
    Proxy_Authorization text,
    Range text,
    Referer text,
    TE text,
    Req_User_Agent text,
    Upgrade text,
    Via text,
    Warning text,
    X_Requested_With text,
    DNT integer,
    X_Forwarded_For text,
    X_Forwarded_Host text,
    X_Forwarded_Proto text,
    Front_End_Https text,
    X_Http_Method_Override text,
    X_ATT_DeviceId text,
    X_Wap_Profile text,
    Proxy_Connection text,
    X_UIDH text,
    X_Csrf_Token text,
    X_Request_ID text,
    X_Correlation_ID text,
    Other text,
    Cur_datetime text,
    Req_url text
);
create table if not exists images (
    name text primary key not null,
    img_type text,
    filename text
);
